#!/usr/bin/env python3
import argparse

from gtk_theme_switcher import GTKThemeSwitcher
from icon_theme_switcher import IconThemeSwitcher
from nvim_theme_switcher import NvimThemeSwitcher


class Main:
    def __init__(self) -> None:
        parser = argparse.ArgumentParser(description ='Get env name')
        parser.add_argument('--component', type=str, required=True)
        parser.add_argument('--theme', type=str, required=True)
        args = parser.parse_args()
        self.comp = args.component
        self.theme = args.theme

    def main(self):
        component_object = None
        if self.comp == 'gtk':
            component_object = GTKThemeSwitcher(self.theme)
        elif self.comp == 'icon':
            component_object = IconThemeSwitcher(self.theme)
        elif self.comp == 'nvim':
            component_object = NvimThemeSwitcher(self.theme)

        component_object.switch_theme()

if __name__ == '__main__':
    Main().main()
